# Generated by Django 3.0.4 on 2020-05-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('producto', models.CharField(max_length=50, verbose_name='Producto')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('masdecuatrounidades', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porHorma', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fraccionado', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'lista',
                'verbose_name_plural': 'listas',
            },
        ),
    ]
