# Generated by Django 3.0.4 on 2020-06-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20200527_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('producto', models.CharField(max_length=50, verbose_name='Producto')),
                ('peso', models.CharField(max_length=100)),
                ('masdecuatrounidades', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porHorma', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fraccionado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'fiambre',
                'verbose_name_plural': 'fiambres',
            },
        ),
    ]
