# Generated by Django 3.0.4 on 2020-06-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20200605_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiambre',
            name='por_pieza',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
    ]
